apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kube-news-ingress #nome do ingress
  namespace: kube-news
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: localhost #endereço do host alvo
    http:
      paths:
       - path: /
         pathType: Prefix
         backend:
          service:
            name: web
            port:
              number: 80