apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kube-news-ingress #nome do ingress
  namespace: kube-news
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: kube-news.net #endereço do host alvo
    http:
      paths:
       - path: /
         backend:
          serviceName: web # nome do service que ira ser apontado
          servicePort: 80